games/urls.py
from django.urls import path

from games.views import (
    MathFactsView,
    AnagramHuntView,
    start_game,
    update_game,
    end_game,
    LeaderboardView,
)

app_name = "games"
urlpatterns = [
    path("math-facts/", MathFactsView.as_view(), name="math-facts"),
    path("anagram-hunt/", AnagramHuntView.as_view(), name="anagram-hunt"),
    path("leaderboard/", LeaderboardView.as_view(), name="leaderboard"),
    path("start/", start_game, name="ajax-start-game"),
    path("update/", update_game, name="ajax-update-game"),
    path("end/", end_game, name="ajax-end-game"),
]

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView, ContactPageView, ContactSuccessView

app_name = "pages"
urlpatterns = [
    path("", HomePageView.as_view(), name="homepage"),
    path("about/", AboutPageView.as_view(), name="aboutpage"),
    path("contact/", ContactPageView.as_view(), name="contactpage"),
    path("contact-success/", ContactSuccessView.as_view(), name="contact_success"),
]

play2learn/urls.py
import private_storage.urls

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    # User Management
    path("account/", include("users.urls")),
    path("account/", include("allauth.urls")),
    # Private media
    path("media/private/", include(private_storage.urls)),
    path("", include("games.urls")),
    path("", include("pages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
<div class="container">
    <div class="row border-top border-2 border-dark">
        <div class="col-lg-6 col-md-12">
            <p class="text-lg-start d-block text-md-center text-light h-100 pt-2">
                © {{ currentYear }} Play2Learn. All rights reserved.
            </p>
        </div>
        <div class="col-lg-6 col-md-12">
            <ul
                class="social d-flex justify-content-center justify-content-lg-end align-items-center list-unstyled h-100">
                {% if user.is_staff %}
                <li class="mx-2">
                    <a href="/admin/" class="text-light"><i class="fas fa-lock"></i></a>
                </li>
                {% endif %}
                <li class="mx-2">
                    <a href="{% url 'pages:aboutpage' %}" class="text-light">
                        <i class="fas fa-info"></i>
                    </a>
                </li>
                <li class="mx-2">
                    <a href="{% url 'pages:contactpage' %}" class="text-light">
                        <i class="fas fa-envelope"></i>
                    </a>
                </li>
                <li class="mx-2">
                    <a href="https://instagram.com" target="_blank" rel="noopener noreferrer" class="text-light">
                        <i class="fab fa-instagram"></i>
                    </a>
                </li>
                <li class="mx-2">
                    <a href="https://twitter.com" target="_blank" rel="noopener noreferrer" class="text-light">
                        <i class="fab fa-twitter"></i>
                    </a>
                </li>
                <li class="mx-2">
                    <a href="https://facebook.com" target="_blank" rel="noopener noreferrer" class="text-light">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

templates/partials/logo.html
<a href="{% url 'pages:homepage' %}" class="navbar-brand" aria-current="page">
    <!-- Header content such as logo, title, etc. -->
    <h1 class="text-light">Play2Learn Logo</h1>
</a>

templates/partials/messages.html
{% if messages %}
<ul>
    {% for message in messages %}
    <div class="alert message{{ message.tags }} alert-dismissible" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

    </div>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
<!-- Main Navigation -->
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light border-bottom border-2 border-dark">
        <!-- Include the logo -->
        {% include 'partials/logo.html' %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a href="{% url 'pages:homepage' %}"
                        class="nav-link {% if request.resolver_match.url_name == 'homepage' %}active{% endif %}">
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'games:leaderboard' %}"
                        class="nav-link {% if request.resolver_match.url_name == 'leaderboard' %}active{% endif %}">
                        Leaderboard
                    </a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link text-light dropdown-toggle" href="#" id="featuresDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Games
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="featuresDropdown">
                        <li>
                            <a href="{% url 'games:math-facts' %}"
                                class="dropdown-item {% if request.resolver_match.url_name == 'math-facts' %}active{% endif %}">
                                Math Facts Practice
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'games:anagram-hunt' %}"
                                class="dropdown-item {% if request.resolver_match.url_name == 'anagram-hunt' %}active{% endif %}">
                                Anagram Hunt
                            </a>
                        </li>
                    </ul>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'account_login' %}active{% endif %}"
                        href="{% url 'account_login' %}">
                        Log in
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'account_signup' %}active{% endif %}"
                        href="{% url 'account_signup' %}">
                        Sign up
                    </a>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Me
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item {% if request.resolver_match.url_name == 'my-account' %}active{% endif %}"
                            href="{% url 'my-account' %}">
                            My Account
                        </a>
                        <a class="dropdown-item {% if request.resolver_match.url_name == 'list-review' %}active{% endif %}"
                            href="{% url 'list-review' %}">
                            My Reviews
                        </a>
                        <a class="dropdown-item {% if request.resolver_match.url_name == 'list-tracking' %}active{% endif %}"
                            href="{% url 'list-tracking' %}">
                            My Tracking History
                        </a>
                        <div class="dropdown-divider"></div>
                        <form method="post" action="{% url 'account_logout' %}">
                            {% csrf_token %}
                            <button class="btn dropdown-item">Log out</button>
                        </form>
                    </div>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

templates/partials/paginator.html
<nav aria-label="pagination"></nav>
<ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link btn-color" href="?page=1">&laquo; 1…</a>
    </li>
    {% if page_obj.previous_page_number != 1 %}
    <li class="page-item">
        <a class="page-link btn-color" href="?page={{ page_obj.previous_page_number }}">
            {{ page_obj.previous_page_number }}
        </a>
    </li>
    {% endif %}
    {% endif %}
    <li class="page-item active">
        <span class="page-link btn-color">
            {{ page_obj.number }}
        </span>
    </li>
    {% if page_obj.has_next %}
    {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
    <li class="page-item">
        <a class="page-link btn-color" href="?page={{ page_obj.next_page_number }}">
            {{ page_obj.next_page_number }}
        </a>
    </li>
    {% endif %}
    <li class="page-item">
        <a class="page-link btn-color" href="?page={{ page_obj.paginator.num_pages }}">
            …{{ page_obj.paginator.num_pages }} &raquo;
        </a>
    </li>
    {% endif %}
</ul>
</nav>