games/urls.py
from django.urls import path

from games.views import (
    MathFactsView,
    AnagramHuntView,
    start_game,
    update_game,
    end_game,
    LeaderboardView,
)

app_name = "games"
urlpatterns = [
    path("math-facts/", MathFactsView.as_view(), name="math-facts"),
    path("anagram-hunt/", AnagramHuntView.as_view(), name="anagram-hunt"),
    path("leaderboard/", LeaderboardView.as_view(), name="leaderboard"),
    path("start/", start_game, name="ajax-start-game"),
    path("update/", update_game, name="ajax-update-game"),
    path("end/", end_game, name="ajax-end-game"),
]

play2learn/urls.py
import private_storage.urls

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    # User Management
    path("account/", include("users.urls")),
    path("account/", include("allauth.urls")),
    # Private media
    path("media/private/", include(private_storage.urls)),
    path("", include("games.urls")),
    path("", include("pages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://kit.fontawesome.com/f804978a2a.js" crossorigin="anonymous"></script>
  {% block javascript %}{% endblock %}

  <!-- Favicon -->
  <link rel="icon" type="image/x-icon" href="{% static 'pages/favicon.ico' %}">

  <title>{% block title %}{% endblock %} | Play Games</title>
</head>

<body>
  <header class="fixed-top shadow">
    <!-- Include the nav -->
    {% include 'partials/nav.html' %}
  </header>

  <div class="container mt-5 pt-5">
    <main class="container">
      <!-- Include the messages -->
      {% include 'partials/messages.html' %}

      {% block main %}<h2>Welcome!</h2>{% endblock %}
    </main>
  </div>

  <footer class="shadow">
    <!-- Include the footer -->
    {% include 'partials/footer.html' %}
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
    crossorigin="anonymous"></script>
</body>

</html>

templates/_base_vue.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS CDN-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script defer src="http://localhost:8080/js/chunk-vendors.js"></script>
  <script defer src="http://localhost:8080/js/app.js"></script>

  {% block javascript %}{% endblock %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- Favicon -->
  <link rel="icon" type="image/x-icon" href="{% static 'games/favicon.ico' %}">

  <title>{% block title %}{% endblock %}</title>

</head>

<body>

  <header class="fixed-top shadow">
    <!-- Include the nav -->
    {% include 'partials/nav.html' %}
  </header>


  <div class="container mt-5 pt-5">
    <main class="container">
      <!-- Include the messages -->
      {% include 'partials/messages.html' %}

      {% block main %}{% endblock %}
      <div id="app"></div>

    </main>
  </div>


  <footer class="shadow">
    <!-- Include the footer -->
    {% include 'partials/footer.html' %}
  </footer>

  <!-- Bootstrap JS CDN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</body>

</html>

templates/anagram-hunt.html
{% extends "_base_vue.html" %}

{% load static %}

{% block javascript %}
<script>
    const ajaxStartURL = "{% url 'games:ajax-start-game' %}";
    const ajaxUpdateURL = "{% url 'games:ajax-update-game' %}";
    const ajaxEndURL = "{% url 'games:ajax-end-game' %}";
    const gameType = "anagram_hunt";
</script>
<script src="{% static 'js/games.js' %}"></script>
{% endblock %}

{% block title %} Anagram Hunt {% endblock %}

{% block main %}
<h1>Anagram Hunt</h1>
{{ block.super }}
{% endblock %}

templates/math-facts.html
{% extends "_base_vue.html" %}

{% load static %}

{% block javascript %}
<script>
  const ajaxStartURL = "{% url 'games:ajax-start-game' %}";
  const ajaxUpdateURL = "{% url 'games:ajax-update-game' %}";
  const ajaxEndURL = "{% url 'games:ajax-end-game' %}";
  const gameType = "math_facts";
</script>
<script src="{% static 'js/games.js' %}"></script>
{% endblock %}

{% block title %}Math Facts{% endblock %}

{% block main %}
<h1>Math Facts</h1>
{{ block.super }}
{% endblock %}